# Generated by Django 4.2.20 on 2025-04-18 18:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='couponuser',
            unique_together={('user', 'coupon')},
        ),
    ]
