# Generated by Django 4.2.20 on 2025-04-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_notification_is_read_remove_notification_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
