# Generated by Django 5.2 on 2025-04-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_created_at_alter_cart_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity_product',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
