# Generated by Django 4.2.20 on 2025-04-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
