# Generated by Django 5.2 on 2025-04-21 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylog',
            old_name='action',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='activitylog',
            old_name='timestamp',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='activitylog',
            old_name='table_affected',
            new_name='type',
        ),
    ]
