# Generated by Django 4.2.20 on 2025-04-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_activitylog_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
