# Generated by Django 4.2.20 on 2025-04-21 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_rename_action_activitylog_description_and_more'),
        ('logs', '0003_activitylog_ip_address'),
    ]

    operations = [
    ]
