# Generated by Django 4.2.20 on 2025-04-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_merge_20250421_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
