# Generated by Django 5.2 on 2025-04-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='nit',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='state',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
    ]
