# Generated by Django 5.2 on 2025-04-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_invoice_nit_invoice_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='razon_social',
            field=models.CharField(default='Ninguna', max_length=50),
        ),
    ]
