# Generated by Django 5.2 on 2025-04-14 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_invoice_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='state',
        ),
    ]
