# Generated by Django 5.2 on 2025-04-14 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_invoice_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingmethod',
            name='estimated_days',
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='estimated_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
