# Generated by Django 4.2.20 on 2025-04-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_shippingmethod_estimated_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='stripe_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
